describe('Cliente', () => {
  it('Cadastrar cliente', () => {
    cy.visit('http://localhost:5173/clientes')
    cy.get('.btnCadastrar').click()
    cy.get('input[name="nome"').type('Cliente 1')
    cy.get('input[name="documento"').type('56.437.025/0001-01')
    cy.contains("Selecione o Estado").click()
    cy.contains("PB").click()
    cy.get('input[name="cidade"').type('João Pessoa')
    cy.get('input[name="email"').type('cliente1@gmail.com')
    cy.get('input[name="telefone"').type('839999999')
    cy.contains("Engenharia Cívil").click()
    cy.get('#endereco').type('Rua Exemplo')
    cy.contains("Situação").click()
    cy.contains("Salvar").click()
    cy.contains("Cliente cadastrado com sucesso")
  })
})
