describe('Cliente', () => {
  it('RF2.12 Cadastrar Cliente', () => {
    cy.visit('http://localhost:5173/')
    cy.contains('Clientes').click()
    cy.get('.btnCadastrar').click()
    cy.contains('Cadastrar Cliente')
    cy.get('input[name="nome"').type('Cliente 1')
    cy.get('input[name="documento"').type('123.914.130-09')
    cy.contains("Selecione o Estado").click()
    cy.contains("PB").click()
    cy.get('input[name="cidade"').type('João Pessoa')
    cy.get('input[name="email"').type('cliente12@gmail.com')
    cy.get('input[name="telefone"').type('839999999')
    cy.contains("Engenharia Cívil").click()
    cy.get('#endereco').type('Rua Exemplo')
    cy.get('#complemento').type('N 123, próximo do XPTO')
    cy.contains("Situação").click()
    cy.contains("Salvar").click()
    cy.contains("Cliente cadastrado com sucesso")
  })
})
