name: 'Build Pipeline'

parameters:
  - name: NODE_VERSION
    type: string
    default: '18.20.2'
    displayName: 'Nodejs version'

# pode ser o nome da branch que se deseja ouvir
trigger:
  - none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: 'spec'
              versionSpec: '${{parameters.NODE_VERSION}}'
            displayName: 'Instalando node'

          - task: Bash@3
            inputs:
              targetType: