describe('Contrato', () => {
    it('Listar Contratos', () => {
        cy.visit('http://localhost:5173/')
        cy.contains('Contratos').click()
   })
   it('Cadastrar Contrato', () => {
        cy.visit('http://localhost:5173/')
        cy.contains('Contratos').click()
        cy.get('.btnCadastrar').click()
        cy.get('input[name="nome"]').type('Serviço Elétrico')
        cy.get('input[placeholder="Orçamento"]').type('8900')
        cy.get('input[name="data_inicio"]').click()
        cy.get('.el-date-table').contains('.available', '4').click()
        cy.get('input[name="data_fim"]').type('21/03/2024')
        cy.contains("Situação").click()
        cy.contains("Salvar").click()
        cy.contains('Contratos').click()       
    })
    it('Excluir contrato', () => {
        cy.visit('http://localhost:5173/contratos')
        cy.contains('Contratos').click()
        cy.contains('Editar').click()
        cy.contains('Excluir').click()
        cy.contains('Confirmar').click()
        cy.contains('Contratos').click()
    })
})