describe('Servico', () => {
  it('RF5 Cadastrar Serviço', () => {
    cy.visit('http://localhost:5173/')
    cy.contains('Serviços').click()
    cy.contains('Cadastrar')
    cy.get('.btnCadastrar').click()
    cy.contains('Selecionar o contrato').click()
    cy.contains('Contrato 1').click()
    cy.get('input[name="descricao"').type('Pintura')
    cy.get('input[name="valor"').type('3400')
    cy.contains("Engenharia Cívil").click()
    cy.contains("Situação").click()
    cy.contains("Salvar").click()
    cy.contains("Serviço cadastrado com sucesso")
  })
})
