describe('Cliente', () => {
  it('Validar duplicidade de email', () => {
    const emailMock = 'cliente1@gmail.com'
    cy.visit('http://localhost:5173/')
    cy.contains('Clientes').click()
    cy.get('.btnCadastrar').click()
    cy.get('input[name="nome"').type('Cliente 1')
    cy.get('input[name="documento"').type('56.437.025/0001-01')
    cy.contains("Selecione o Estado").click()
    cy.contains("PB").click()
    cy.get('input[name="cidade"').type('João Pessoa')
    cy.get('input[name="email"').type(emailMock)
    cy.get('input[name="telefone"').type('839999999')
    cy.contains("Engenharia Cívil").click()
    cy.get('#endereco').type('Rua Exemplo')
    cy.contains("Situação").click()
    cy.contains("Salvar").click()
    cy.contains("Cliente cadastrado com sucesso")

    cy.visit('http://localhost:5173/clientes')
    cy.get('.btnCadastrar').click()
    cy.get('input[name="email"').type(emailMock)
    cy.get('input[name="telefone"').click()
    cy.contains('Atenção')
    cy.contains(`Já existe um cliente com este email ${emailMock}`)
  })
})
