export enum RolesEnum {
    ANY = '*',
    MASTER = 'MASTER',
    // Cliente
    LISTAR_CLIENTE = 'LISTAR_CLIENTE',
    CADASTRAR_CLIENTE = 'CADASTRAR_CLIENTE',
    EDITAR_CLIENTE = 'EDITAR_CLIENTE',
    EXCLUIR_CLIENTE = 'EXCLUIR_CLIENTE',
    // Setor
    SETOR_LISTAR = 'SETOR_LISTAR',
    SETOR_CADASTRAR = 'SETOR_CADASTRAR',
    SETOR_EDITAR = 'SETOR_EDITAR',
    SETOR_EXCLUIR = 'SETOR_EXCLUIR',
    // Contrato
    CONTRATO_LISTAR = 'CONTRATO_LISTAR',
    CONTRATO_CADASTRAR = 'CONTRATO_CADASTRAR',
    CONTRATO_EDITAR = 'CONTRATO_EDITAR',
    CONTRATO_EXCLUIR = 'CONTRATO_EXCLUIR',
    // Projeto
    PROJETO_LISTAR = 'PROJETO_LISTAR',
    PROJETO_CADASTRAR = 'PROJETO_CADASTRAR',
    PROJETO_EDITAR = 'PROJETO_EDITAR',
    PROJETO_EXCLUIR = 'PROJETO_EXCLUIR',
    // Servico
    SERVICO_LISTAR = 'SERVICO_LISTAR',
    SERVICO_CADASTRAR = 'SERVICO_CADASTRAR',
    SERVICO_EDITAR = 'SERVICO_EDITAR',
    SERVICO_EXCLUIR = 'SERVICO_EXCLUIR',
    // Ordem de Serviço
    ORDEM_SERVICO_LISTAR = 'ORDEM_SERVICO_LISTAR',
    ORDEM_SERVICO_CADASTRAR = 'ORDEM_SERVICO_CADASTRAR',
    ORDEM_SERVICO_EDITAR = 'ORDEM_SERVICO_EDITAR',
    ORDEM_SERVICO_EXCLUIR = 'ORDEM_SERVICO_EXCLUIR',
    // Recursos Humanos
    COLABORADOR_LISTAR = 'COLABORADOR_LISTAR',
    COLABORADOR_CADASTRAR = 'COLABORADOR_CADASTRAR',
    COLABORADOR_EDITAR = 'COLABORADOR_EDITAR',
    COLABORADOR_EXCLUIR = 'COLABORADOR_EXCLUIR',
    // Fornecedor
    FORNECEDOR_LISTAR = 'FORNECEDOR_LISTAR',
    FORNECEDOR_CADASTRAR = 'FORNECEDOR_CADASTRAR',
    FORNECEDOR_EDITAR = 'FORNECEDOR_EDITAR',
    FORNECEDOR_EXCLUIR = 'FORNECEDOR_EXCLUIR',
    // Usuário
    LISTAR_USUARIO = 'LISTAR_USUARIO',
    CADASTRAR_USUARIO = 'CADASTRAR_USUARIO',
    EDITAR_USUARIO = 'EDITAR_USUARIO',
    EXCLUIR_USUARIO = 'EXCLUIR_USUARIO',
}

