export enum RolesEnum {
    ANY = '*',
    MASTER = 'MASTER',
    // Cliente
    CLIENTE_LISTAR = 'CLIENTE_LISTAR',
    CLIENTE_CADASTRAR = 'CLIENTE_CADASTRAR',
    CLIENTE_EDITAR = 'CLIENTE_EDITAR',
    CLIENTE_EXCLUIR = 'CLIENTE_EXCLUIR',
    // Setor
    SETOR_LISTAR = 'SETOR_LISTAR',
    SETOR_CADASTRAR = 'SETOR_CADASTRAR',
    SETOR_EDITAR = 'SETOR_EDITAR',
    SETOR_EXCLUIR = 'SETOR_EXCLUIR',
    // Contrato
    CONTRATO_LISTAR = 'CONTRATO_LISTAR',
    CONTRATO_CADASTRAR = 'CONTRATO_CADASTRAR',
    CONTRATO_EDITAR = 'CONTRATO_EDITAR',
    CONTRATO_EXCLUIR = 'CONTRATO_EXCLUIR',
    // Projeto
    PROJETO_LISTAR = 'PROJETO_LISTAR',
    PROJETO_CADASTRAR = 'PROJETO_CADASTRAR',
    PROJETO_EDITAR = 'PROJETO_EDITAR',
    PROJETO_EXCLUIR = 'PROJETO_EXCLUIR',
    // Servico
    SERVICO_LISTAR = 'SERVICO_LISTAR',
    SERVICO_CADASTRAR = 'SERVICO_CADASTRAR',
    SERVICO_EDITAR = 'SERVICO_EDITAR',
    SERVICO_EXCLUIR = 'SERVICO_EXCLUIR',
    // Ordem de Serviço
    ORDEM_SERVICO_LISTAR = 'ORDEM_SERVICO_LISTAR',
    ORDEM_SERVICO_CADASTRAR = 'ORDEM_SERVICO_CADASTRAR',
    ORDEM_SERVICO_EDITAR = 'ORDEM_SERVICO_EDITAR',
    ORDEM_SERVICO_EXCLUIR = 'ORDEM_SERVICO_EXCLUIR'
}

